Update patch set 5
Patch Set 5: Code-Review-1

E/AndroidRuntime( 9143): FATAL EXCEPTION: main
E/AndroidRuntime( 9143): Process: com.android.settings, PID: 9143
E/AndroidRuntime( 9143): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.android.settings.kangdroid.VolumeSteps: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime( 9143): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
E/AndroidRuntime( 9143): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
E/AndroidRuntime( 9143): 	at android.app.ActivityThread.access$900(ActivityThread.java:147)
E/AndroidRuntime( 9143): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
E/AndroidRuntime( 9143): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9143): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9143): 	at android.app.ActivityThread.main(ActivityThread.java:5266)
E/AndroidRuntime( 9143): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9143): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9143): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime( 9143): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/AndroidRuntime( 9143): Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.android.settings.kangdroid.VolumeSteps: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime( 9143): 	at android.app.Fragment.instantiate(Fragment.java:618)
E/AndroidRuntime( 9143): 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:961)
E/AndroidRuntime( 9143): 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:601)
E/AndroidRuntime( 9143): 	at android.app.Activity.performCreate(Activity.java:5940)
E/AndroidRuntime( 9143): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 9143): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
E/AndroidRuntime( 9143): 	... 10 more
E/AndroidRuntime( 9143): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settings.kangdroid.VolumeSteps" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 9143): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 9143): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 9143): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 9143): 	at android.app.Fragment.instantiate(Fragment.java:604)
E/AndroidRuntime( 9143): 	... 15 more
E/AndroidRuntime( 9143): 	Suppressed: java.lang.ClassNotFoundException: com.android.settings.kangdroid.VolumeSteps
E/AndroidRuntime( 9143): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 9143): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 9143): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 9143): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 9143): 		... 17 more
E/AndroidRuntime( 9143): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Patch-set: 5
Label: Code-Review=-1